[package]
name = "TMC2209_pi"
version = "0.1.0"
edition = "2021"
authors = ["Mike Rouleau"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
