[package]
name = "tmc2209_pi"
version = "0.1.0"
edition = "2021"
authors = ["Mike Rouleau <44850854+mikerouleau@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"